# hotfix for windows
# build image by: docker build -t openhackathons:ai-for-science-hotfix - <./Dockerfile.hotfix

FROM openhackathons:ai-for-science

RUN rm -rf \
    /usr/lib/x86_64-linux-gnu/libcuda.so* \
    /usr/lib/x86_64-linux-gnu/libnvcuvid.so* \
    /usr/lib/x86_64-linux-gnu/libnvidia-*.so* \
    /usr/lib/firmware \
    /usr/local/cuda/compat/lib